### ISSUE TITLE
recording videos

### ISSUE THREAD

**Issue by dragonxtek** [JFF-Bohdan/pynvr#1]
It detects movement and the record folder is ./video (default folder).
After a lot detections, the video folder is yet empty.
How I can get more info to detect where is the problem?
I'm using ubuntu 16.04
Thanks

**Comment by dragonxtek** [comment]
FIXED: 
Replace FOURCC_CODEC = "DIVX" 
by 
FOURCC_CODEC = "MJPG"

**Comment by JFF-Bohdan** [comment]
Hello, 

Yes it's OK. This is not a FIX actually. It's just option which able to work at your configuration: OS, codecs. MJPG is not a good choice, you shall look for something better than MJPG which will work at your configuration. Also, you may find problems with looking for working configuration - container + codec.

But MJPG is a simplest configuration which can work at all platforms.

Thank you.
